<a href="https://colab.research.google.com/github/iskalinov13/DCVW-Labs/blob/main/LAB3_DCVW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1

**In part 1 you need to work with data from the about 120 years of Olympic history by pandas. Write code and perform computations in the cells below. There are five questions.** 

Download the file `athlete_events.csv` from [here](https://drive.google.com/file/d/1f5v6Z2ayc7h698FG_98wP5x1Y2zZQeox/view?usp=sharing). The dataset has the following features:

- __ID__ - Unique number for each athlete
- __Name__ - Athlete's name
- __Sex__ - M or F
- __Age__ - Integer
- __Height__ - In centimeters
- __Weight__ - In kilograms
- __Team__ - Team name
- __NOC__ - National Olympic Committee 3-letter code
- __Games__ - Year and season
- __Year__ - Integer
- __Season__ - Summer or Winter
- __City__ - Host city
- __Sport__ - Sport
- __Event__ - Event
- __Medal__ - Gold, Silver, Bronze, or NA

In [ ]:
import pandas as pd
from google.colab import drive
drive.mount("/drive") 

Mounted at /drive


In [ ]:
PATH = 'athlete_events.csv'

In [ ]:
data = pd.read_csv('/drive/My Drive/athlete_events.csv')
data.head()

ID                      Name  ...                             Event  Medal
0   1                 A Dijiang  ...       Basketball Men's Basketball    NaN
1   2                  A Lamusi  ...      Judo Men's Extra-Lightweight    NaN
2   3       Gunnar Nielsen Aaby  ...           Football Men's Football    NaN
3   4      Edgar Lindenau Aabye  ...       Tug-Of-War Men's Tug-Of-War   Gold
4   5  Christine Jacoba Aaftink  ...  Speed Skating Women's 500 metres    NaN

[5 rows x 15 columns]

__1. How old were the oldest male and female participants of the 2012 Olympics?__

In [ ]:
res1 = data[data['Year'] == 2012].groupby('Sex')['Age'].max()
res1


Sex
F    57.0
M    71.0
Name: Age, dtype: float64

__2. What are the mean and standard deviation of height for male basketball players who participated in the 1992 Olympics? Round the answer to the first decimal.__

In [ ]:
res2 = data[(data['Year'] == 1992) & (data['Sex'] == 'M') & (data['Sport'] == 'Basketball')]['Height'].describe().round(1)
print('Mean is: ',res2[1])
print('Standard Deviation is: ',res2[2])

Mean is:  199.5
Standard Deviation is:  9.5


__3. How many times did Christine Jacoba Aaftink participate in the Olympics held in different years?__

In [ ]:
res3 = data[data['Name'] == 'Christine Jacoba Aaftink'].groupby('Year').Year.count()
res3.shape[0]

3

__4. Is it true that China won fewer medals than Russia at the 2012 Olympics? Do not consider NaN values in Medal column.__

In [ ]:
res4 = data[(data['Year'] == 2012) & (data['Medal'] != 'NaN')]
res4[(res4['Team']=='China')].shape[0] < res4[(res4['Team']=='Russia')].shape[0]

True

__5. What is the absolute difference between the number of unique sports at the 1986 Olympics and 2016 Olympics?__

In [ ]:
res5 = abs(data[data['Year']==2016]['Sport'].nunique() - data[data['Year']==1986]['Sport'].nunique())
res5
data[data['Year']==2016]['Sport'].nunique()

34

# Part 2

**In part 2 you need to work with numpy library. Write code and perform computations in the cells below. There are five questions.** 

In [ ]:
import numpy as np

__6. Create a 5x5 matrix with row values ranging from 0 to 4__

In [ ]:
matrix = np.zeros((5,5))
matrix += np.arange(5)
matrix

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

__7. Create a random vector of size 10 and sort it__

In [ ]:
matrix = np.random.random(10)
print("Original array:")
print(matrix)
matrix.sort()
print("Sorted array:")
print(matrix)

Original array:
[0.17620158 0.78873032 0.04251632 0.93802442 0.64121953 0.27284212
 0.74083732 0.92305669 0.93487031 0.753569  ]
Sorted array:
[0.04251632 0.17620158 0.27284212 0.64121953 0.74083732 0.753569
 0.78873032 0.92305669 0.93487031 0.93802442]


__8. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area__

> Блок с отступами



In [ ]:
matrix = np.zeros((10,10), [('x',float),('y',float)])
matrix['x'], matrix['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(matrix)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

__9. Consider two random array A and B, check if they are equal__

In [ ]:
mat1 = np.random.randint(0,3,9)
print("First array:")
print(mat1)
mat2 = np.random.randint(0,3,9)
print("Second array:")
print(mat2)
print("Test if they are equal?")
np.allclose(mat1, mat2)


First array:
[2 0 1 0 0 2 1 0 1]
Second array:
[2 2 2 1 1 2 1 0 1]
Test if they are equal?


False

__10. Create a random matrix and swap two rows of an array?__

In [ ]:
matrix = np.array([[5, 4, 1],[3 ,0, 0],[1, 1, 3],[7, 2, 6]])
print("Initial array:")
print(matrix)
matrix[[0, 2]] = matrix[[2, 0]]
print("After swapping:")
print(matrix)

Initial array:
[[5 4 1]
 [3 0 0]
 [1 1 3]
 [7 2 6]]
After swapping:
[[1 1 3]
 [3 0 0]
 [5 4 1]
 [7 2 6]]
